### ISSUE TITLE
Cannot find img or diagrams folder 

### ISSUE THREAD

**Issue by Genysys** [drandreaskrueger/chainhammer#10]
*Operating System*: Debian 9

## Details
After running chainhammer i.e.

```
CH_TXS=40000 CH_THREADING="threaded2 300" ./run.sh "Quorum_t2.xlarge_8Mgas_5s_Blocktime"
```
the programs says the diagrams should be available here:
`img/Quorum_t2.xlarge_8Mgas_5s_Blocktime-20191001-1020_blks219-237.png`
but I cannot seem to find them.

I have also checker under `reader` but cant find a digram file as the `README.md` suggests

**Comment by drandreaskrueger** [comment]
Perhaps: Is there no `chainhammer/reader/img/` folder? If not, then you create one, and rerun. 

Please notify me if that was the reason.

**Comment by Genysys** [comment]
Hi,

Upon closer inspection i noticed this:

```
Single block, vs averaged over 10 blocks:
peak( TPS_1blk) = 59.20 
peak(TPS_10blk) = nan


Less than 2 blocks filled. So: NOT generating diagram!
Premature ending. You probably do not want this.
Done.

=============================
= page_generator.py
=============================
Reading from INFOFILE ../hammer/last-experiment.json and from TPSLOG ../logs/tps.py.log
Page saved to:  ../results/runs/Quorum_20191014-1341_txs40000.md
Page saved to:  ../results/runs/Quorum_20191014-1341_txs40000.html
```

What is causing less than 2 blocks to be filled? I am starting off with sending 40k transactions, 5 second blocktime and 8m gas. I do notice a significant number of pending transactions( > 20K) . after the results are printed. could this be the issue?

**Comment by drandreaskrueger** [comment]
Yes, without data no diagrams.

When the hammer script is running, can you see blocks getting accepted?

Would you please redo it, and drop the log files here:

* tps.py.log
* send.py.log
* deploy.py.log

Thanks a lot, esp for getting back to me. Much appreciated.
