### ISSUE TITLE
Comments on new tool. 

### ISSUE THREAD

**Issue by Genysys** [drandreaskrueger/chainhammer#16]
Hi,

I am trying to reach you for comments on a tool we have built for testing blockchain. We have integrated chain hammer into it and would love your comments.  I do not want to litter your issues page with links to another repo, and therefore be deeply appreciative of a means of reaching you.

**Comment by drandreaskrueger** [comment]
Very nice. 

Your github profile gives no means of contacting you.  
Please tell me your email address. Or DM me on twitter.

**Comment by Genysys** [comment]
Forgot  was already following you on twitter. Not able to DM you so I have sent you a tweet.
