### ISSUE TITLE
RPCaddress; how to talk to an Ethereum node, tutorial resources

### ISSUE THREAD

**Issue by Mohammed-alzuharey** [drandreaskrueger/chainhammer#22]
Hello Dr 
I installed the chainhammer on my machine as you told me using
  scripts/install.sh docker Ubuntu  
and i implemented first test  
CH_TXS=1000 CH_THREADING="sequential" ./run.sh $HOSTNAME-TestRPC testrpc 
Every things fine 
Then implemented 7nodes quorum example locally on machine 
OS: Ubuntu 20.04 virtual machine 
consensus algorithm : clique 
transaction : send private transaction between node1 and node7 as follow 
mohamed@mohamed-VirtualBox:~/quorum-examples/examples/7nodes$ ./runscript.sh private-contract.js
Contract transaction send: TransactionHash: 0xf734748a660ada751edf7736311137b0eac76dcebab71d8889e9928cd6059751 waiting to be mined...
true
Now , how use chainhammer to test  performance of my local network (7nodes example ) ? thanks

**Comment by drandreaskrueger** [comment]
:+1:

**Comment by drandreaskrueger** [comment]
> how use

First set it all up: https://github.com/drandreaskrueger/chainhammer/issues/21#issuecomment-707997775  

Then using your own network work through the step by step procedure https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt

**Comment by Mohammed-alzuharey** [comment]
Good morning Dr 
I executed all steps which told me in: #21    and install chainhammer_nodocker and run first test 
CH_TXS=200 CH_THREADING="sequential" ./run.sh TestRPC testrpc
all things good  (See that image, and those .md and .html pages)
but when go to change ports and execute (./is_up.py)  command I waiting for long time without result as follow :- 
mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ git reset HEAD hammer/config.py
Unstaged changes after reset:
M	reader/blocksDB_create.py
M	scripts/install-virtualenv.sh
mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ git checkout -- hammer/config.py
mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ head -n 20 hammer/config.py
#!/usr/bin/env python3
"""
@summary: settings

@version: v58 (12/April/2019)
@since:   8/May/2018
@organization:
@author:  https://github.com/drandreaskrueger
@see:     https://github.com/drandreaskrueger/chainhammer for updates
"""

##########
# Choices:

# better keep the same port :8545 everywhere, and instead
# patch the docker-compose.yml files, see ../networks/quorum-configure.sh
RPCaddress='http://localhost:8545'
RPCaddress2='http://localhost:8545'

# use this for unittesting with TestRPCProvider
mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ sed -i "s/RPCaddress='http:\/\/localhost:8545'/RPCaddress='https:\/\/jtessera.blockchain.azure.com:3200\/fqlf6UcrcBJPQjoX5RkAx3Nv'/g" hammer/config.py
mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ sed -i "s/RPCaddress2='http:\/\/localhost:8545'/RPCaddress2='https:\/\/jtessera.blockchain.azure.com:3200\/fqlf6UcrcBJPQjoX5RkAx3Nv'/g" hammer/config.py
mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ head -n 20 hammer/config.py
#!/usr/bin/env python3
"""
@summary: settings

@version: v58 (12/April/2019)
@since:   8/May/2018
@organization:
@author:  https://github.com/drandreaskrueger
@see:     https://github.com/drandreaskrueger/chainhammer for updates
"""

##########
# Choices:

# better keep the same port :8545 everywhere, and instead
# patch the docker-compose.yml files, see ../networks/quorum-configure.sh
RPCaddress='https://jtessera.blockchain.azure.com:3200/fqlf6UcrcBJPQjoX5RkAx3Nv'
RPCaddress2='https://jtessera.blockchain.azure.com:3200/fqlf6UcrcBJPQjoX5RkAx3Nv'
# use this for unittesting with TestRPCProvider
mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ source env/bin/activate
(env) mohamed@mohamed-VirtualBox:~/chainhammer_nodocker$ cd hammer
(env) mohamed@mohamed-VirtualBox:~/chainhammer_nodocker/hammer$ ./is_up.py
how can solve this problem ? Thanks for  your attention

**Comment by drandreaskrueger** [comment]
> ./run.sh TestRPC testrpc  
> all things good 

nice one. 

So we have indeed solved for you the problems of the previous issue. https://github.com/drandreaskrueger/chainhammer/issues/21 . Great.

Chainhammer on your machine ... is working. Good.

---

> when go to change ports and execute `./is_up.py` command I waiting for long time 

Yes, you have to fix that first.

Until `./is_up.py` is working fine, nothing else will.

On which port is the RPC of you network node?  Is your RPC open?

The page `docs/azure.md` gives some hints too.

---

Your questions look to me as if your knowledge about Ethereum is very limited.

Perhaps you have to put in some learning first. 

Do some reading, about Ethereum, the RPC API, etc. 

[How to use the Ethereum RPC API](https://www.google.com/search?q=How+to+use+the+Ethereum+RPC+API)

And why not also work through some tutorials?

---

The formatting of your issue text is really strange.

Use triple back-ticks to show code. 

Learn this: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by drandreaskrueger** [comment]
If you get this call working on your network, the is_up.py should work too, and likely everything else too:

(True, None) <-- [simple_RPC_call()](https://github.com/drandreaskrueger/chainhammer/blob/8325afed78390b625977f8e19c5faae16e81fd67/hammer/is_up.py#L52-L71) <-- [curl_post()](https://github.com/drandreaskrueger/chainhammer/blob/695700cb314b5ab15393b39b9025564e55dac4e1/hammer/clienttype.py#L44-L65) <-- RPCaddress

**Comment by Mohammed-alzuharey** [comment]
Good morning Dr
Thank you for advises ... If i implemented local quorum network (7nodes examples ) on my system (Ubuntu vm 20.04)
Can i test it on  chainhammer using next commands :-
 CH_TXS=20000 CH_THREADING="threaded2 20" ./run.sh yourNaming geth-clique
OR 
export CH_MACHINE=QUORUM
./run-all_small.sh 
Thanks

**Comment by drandreaskrueger** [comment]
No

**Comment by drandreaskrueger** [comment]
go back up to here: https://github.com/drandreaskrueger/chainhammer/issues/22#issuecomment-710885885

**Comment by Mohammed-alzuharey** [comment]
Ok ... I read on RPC API as you told me . and this command dont work on my device and still have same problem I mean cannot connect with azure cloud using ./is_up.py 😔

**Comment by drandreaskrueger** [comment]
yes you have to solve this first

https://github.com/drandreaskrueger/chainhammer/issues/22#issuecomment-712723412

**Comment by drandreaskrueger** [comment]
until you can talk to your network via RPC, nothing will work.

**Comment by Mohammed-alzuharey** [comment]
Good night Dr 
I tried many times and patched the RPCaddress'es from localhost:8545 to jtessera.blockchain.azure.com:3200 using 
vim quorum-configure.sh command as follow : 
echo git checkout eeb63a91b7eda0180c8686f819c0dd29c0bc4d46
git checkout eeb63a91b7eda0180c8686f819c0dd29c0bc4d46
# nice: blk-io merged my patches into 
# https://github.com/blk-io/crux/commit/ddd126e62f1f0dac341b2b61b01688f1d960dbd2
# echo patch: raise gasLimit
# jq '.gasLimit = "0x1312D00"' istanbul-genesis.json > tmp && mv tmp istanbul-genesis.json
# echo patch: larger txpool, blockperiod 1 second
# sed -i 's/PRIVATE_CONFIG/ARGS=$ARGS"--txpool.globalslots 50000 --txpool.globalqueue 50000 --istanbul.blockperiod 1 "\nPRIVATE_CONFIG/g' istanbul-start.sh
echo patch: port 22001 change to 8545
sed -i 's/22001:22000/8545:22000/g' docker-compose-local.yaml
echo patch: port 8545 change to 3200
sed -i "s/RPCaddress='http:\/\/localhost:8545'/RPCaddress='https:\/\/jtessera.blockchain.azure.com:3200\/fqlf6UcrcBJPQjoX5RkAx3Nv'/g" docker-compose.yml
sed -i "s/RPCaddress2='http:\/\/localhost:8545'/RPCaddress2='https:\/\/jtessera.blockchain.azure.com:3200\/fqlf6UcrcBJPQjoX5RkAx3Nv'/g" docker-compose.yml
cd $GETBACK

And check connection using mohamed@mohamed-VirtualBox:~$ telnet localhost 8545 
Trying 127.0.0.1...
Connected to localhost.

but still same problem ... what you suggestions for me ?  Thanks

**Comment by Mohammed-alzuharey** [comment]
Good night Dr 
I tried many times and patched the RPCaddress'es from localhost:8545 to jtessera.blockchain.azure.com:3200 by adding  
sed -i "s/RPCaddress='http:\/\/localhost:8545'/RPCaddress='https:\/\/jtessera.blockchain.azure.com:3200\/fqlf6UcrcBJPQjoX5RkAx3Nv'/g" hammer/config.py

sed -i "s/RPCaddress2='http:\/\/localhost:8545'/RPCaddress2='https:\/\/jtessera.blockchain.azure.com:3200\/fqlf6UcrcBJPQjoX5RkAx3Nv'/g" hammer/config.py
to quorum-configure.sh  file 

and check the connection of localhost using : telnet localhost 8545command 
Trying 127.0.0.1 ...
connected to localhost .
but still same problem .... what you suggestions for me ? thanks

**Comment by drandreaskrueger** [comment]
I have created a new simplified testing script for you, and [linked to it in the instructions](https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt): 

* download [test_RPC.py](https://github.com/drandreaskrueger/chainhammer/blob/master/hammer/test_RPC.py)
* `pip3 install requests`
* `python3 test_RPC.py` in terminal 1
* `geth --rpc --dev` in a new terminal 2
* press ENTER in terminal 1

May that help you. 

Keep on learning about Ethereum, and about your network ... until that script runs through and shows "Yes, full success...".

**Comment by Mohammed-alzuharey** [comment]
Good morning Dr ... Thank you for response 
I downloaded  test_RPC.py  and installed pip3 
put  when run command in terminal 1 get error as follow 
mohamed@mohamed-VirtualBox:~$ python3 test_RPC.py
Start a network node, for example by:
    geth --rpc --dev
Press ENTER when ready

Using 'http://localhost:8545' to query RPC, with payload '{'method': 'web3_clientVersion', 'params': [], 'jsonrpc': '2.0', 'id': 1}'
Bad: (<class 'requests.exceptions.ConnectionError'>) HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1611644c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Try again...

**Comment by drandreaskrueger** [comment]
Yes, you must now fix that. Exactly. That's why I built that script for you.

If you cannot fix it yourself, I suggest you find someone else who can. Perhaps even consider to pay someone?
