### ISSUE TITLE
ubuntu

### ISSUE THREAD

**Issue by sherrygarg** [drandreaskrueger/chainhammer#6]
while running 

scripts/install.sh

getting error 

E: Unable to locate package libsecp256k1-dev

and installation stops...

**Comment by drandreaskrueger** [comment]
which Linux are you on?

**Comment by drandreaskrueger** [comment]
Perhaps Ubuntu?

--> https://github.com/drandreaskrueger/chainhammer/commit/b3e6a1bbc19cc8a51c9f8d7a91e79cf878200efa

**Comment by drandreaskrueger** [comment]
Please try this:

https://github.com/drandreaskrueger/chainhammer#quickstart

> (on Ubuntu instead: scripts/install.sh docker ubuntu )

**Comment by drandreaskrueger** [comment]
And? @sherrygarg did that help?

**Comment by sherrygarg** [comment]
@drandreaskrueger  no...still same error

**Comment by sherrygarg** [comment]
do i need to install docker first? since i cloned quorum examples code doesn't that have docker already in it?

**Comment by drandreaskrueger** [comment]
Yes, docker is needed (unless you want to only do remote benchmarking), but it does gets installed via this script:

    scripts/install.sh docker ubuntu

if you are on Ubuntu or

    scripts/install.sh 

if you are on Debian.

Please execute that, and report the output. Thanks.

**Comment by drandreaskrueger** [comment]
which Linux are you on?

**Comment by drandreaskrueger** [comment]
Please read the documents which are linked at the last line of this chapter:

https://github.com/drandreaskrueger/chainhammer#quickstart

**Comment by sherrygarg** [comment]
list of commands I executed

vagrant ssh
`cd quorum-examples/7nodes`
git clone https://github.com/drandreaskrueger/chainhammer CH
```
sudo apt install python3-pip libssl-dev
sudo pip3 install virtualenv 
virtualenv -p python3 py3eth
source py3eth/bin/activate

python3 -m pip install --upgrade pip==18.0
pip3 install --upgrade py-solc==2.1.0 web3==4.3.0 web3[tester]==4.3.0 rlp==0.6.0 eth-testrpc==1.3.4 requests pandas jupyter ipykernel matplotlib
ipython kernel install --user --name="Python.3.py3eth"

```
source py3eth/bin/activate

touch account-passphrase.txt
./deploy.py 
```

on executing deploy.py it says
**Dependencies unavailable. Start virtualenv first!**

Also running 
scripts/install.sh
 or
scripts/install.sh docker ubuntu
says same thing

E: Unable to locate package libsecp256k1-dev

**Comment by drandreaskrueger** [comment]
which Linux are you on?

**Comment by drandreaskrueger** [comment]
They broke `geth`, that is probably the problem, because then my install script does not run through.

Let's wait, what they answer:

https://github.com/ethereum/go-ethereum/issues/19890

**Comment by drandreaskrueger** [comment]
next time PLEASE include the whole output, then we might have found the problem earlier. thanks.

**Comment by drandreaskrueger** [comment]
`geth` is needed for interactive stuff only. Until they have fixed their new `geth` problem, let's just leave it out.

Do this:

```
git clone https://github.com/drandreaskrueger/chainhammer CH
cd CH

nano scripts/install.sh 
```
comment out line 83

```
# install_chapter scripts/install-geth.sh
```
then start the installer, and a first test run
```
scripts/install.sh 
CH_TXS=1000 CH_THREADING="sequential" ./run.sh $HOSTNAME-TestRPC testrpc
``` 

then watch. be patient.

It should end with 
```
Stopped network.

=============================
= Ready.
=============================
See that image, and those .md and .html pages.
```

if that works, then the other manuals in the repo will help you.

please give feedback how this goes. thanks.

**Comment by sherrygarg** [comment]
![scripts_install_prob](https://user-images.githubusercontent.com/19944261/61926336-cf056e80-af8d-11e9-9cb1-56187623f805.jpg)

**Comment by sherrygarg** [comment]
still same :(

**Comment by drandreaskrueger** [comment]
https://github.com/drandreaskrueger/chainhammer/issues/6#issuecomment-513298673

https://github.com/drandreaskrueger/chainhammer/issues/6#issuecomment-514856275

which Linux are you on?

```
uname -a
Linux ... 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
```

**Comment by sherrygarg** [comment]
Linux ubuntu-xenial 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by drandreaskrueger** [comment]
thx.

**Ubuntu.**

As I said before, then you definitely have to run it NOT like this https://github.com/drandreaskrueger/chainhammer/issues/6#issuecomment-515075641

but with the one line changed to

    scripts/install.sh docker ubuntu

please try again.

And copy the whole output below. thanks.

**Comment by Genysys** [comment]
Just had this problem. Use Ubuntu 18.04 and it will work. you will also get problems with the web3 libraries. They have a dependency on `python =>3.5.3 <4.0` The  library that comes with that is `3.5.2` and really not worth the heart ache trying to change it

**Comment by drandreaskrueger** [comment]
Thanks a lot, hope that somehow helps @sherrygarg . Sorry, not an Ubuntu guy, me likes Debian.

As usual, if you find solutions for any edge-case, please submit a merge request. Thanks!

**Comment by drandreaskrueger** [comment]
ubuntu can now be selected in the install scripts:

https://github.com/drandreaskrueger/chainhammer/blob/ebfd5b0052deb9e4f3c22c79c22d9da1e0210132/scripts/install.sh#L10

https://github.com/drandreaskrueger/chainhammer/blob/739dcb32a1c7f1d481898f551e1f2c56739277d8/scripts/install-docker.sh#L8-L13

https://github.com/drandreaskrueger/chainhammer/blob/739dcb32a1c7f1d481898f551e1f2c56739277d8/scripts/install-docker.sh#L37-L39
