### ISSUE TITLE
raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zhjzcbm** [drandreaskrueger/chainhammer#7]
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![image](https://user-images.githubusercontent.com/52943393/62528521-8d1ed700-b86f-11e9-91a4-bf0ce55ef2c6.png)

**Comment by drandreaskrueger** [comment]
Thanks a lot for that issue.

In which context does this error appear?

Can you please run it again, and copy the whole output here. Thanks.

**Comment by drandreaskrueger** [comment]
can I close this issue?
