### ISSUE TITLE
I made a mirror with DOCKER. How can I share it with you?

### ISSUE THREAD

**Issue by zhjzcbm** [drandreaskrueger/chainhammer#9]
`docker pull zhjzcbm/quorum-tps-test`

**Comment by drandreaskrueger** [comment]
Great. Found it: https://hub.docker.com/r/zhjzcbm/quorum-tps-test

How do I use it?
Would you share your Dockerfile?

Thanks.

**Comment by drandreaskrueger** [comment]
hello?
